#!/bin/sh

sxhkd &

bspc monitor -d acme term inet chat mdia misc

bspc config border_width         4
bspc config window_gap           10

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color  "#ececec"
bspc config focused_border_color "#546e7a"

bspc config click_to_focus button1
bspc config swallow_first_click true
